-- =============================================================
-- Folders (Google Drive style) — DRAFT SCHEMA ONLY
-- Chưa triển khai trong app. Chạy migration này khi sẵn sàng build UI/API.
-- =============================================================
--
-- Thiết kế:
-- - Cây thư mục lồng nhau (parent_id self-reference)
-- - Mỗi user có namespace riêng
-- - documents.folder_id = NULL nghĩa là nằm ở root
-- - Xóa folder: CASCADE xóa folder con; documents.folder_id SET NULL hoặc CASCADE tuỳ policy
--
-- CREATE TABLE IF NOT EXISTS folders (
--   id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
--   parent_id   UUID REFERENCES folders(id) ON DELETE CASCADE,
--   name        TEXT NOT NULL,
--   color       TEXT,
--   created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
--   updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
--   UNIQUE (user_id, parent_id, name)
-- );
--
-- CREATE INDEX IF NOT EXISTS idx_folders_user_id ON folders(user_id);
-- CREATE INDEX IF NOT EXISTS idx_folders_parent_id ON folders(parent_id);
--
-- ALTER TABLE documents ADD COLUMN IF NOT EXISTS folder_id UUID REFERENCES folders(id) ON DELETE SET NULL;
-- CREATE INDEX IF NOT EXISTS idx_documents_folder_id ON documents(folder_id);
--
-- ALTER TABLE folders ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "user_owns_folders" ON folders
--   FOR ALL USING (user_id = auth.uid());
--
-- -- Helper: breadcrumb path (materialized path optional for deep trees)
-- -- CREATE TABLE folder_paths (
-- --   folder_id UUID REFERENCES folders(id) ON DELETE CASCADE,
-- --   ancestor_id UUID REFERENCES folders(id) ON DELETE CASCADE,
-- --   depth INT NOT NULL,
-- --   PRIMARY KEY (folder_id, ancestor_id)
-- -- );
